export const recipes = [
  {
    id: 1,
    title: "Spaghetti Carbonara",
    description: "Klassische italienische Pasta mit cremiger Ei-Käse-Sauce",
    image: "/placeholder.svg?height=200&width=300",
    cookTime: 20,
    servings: 4,
    difficulty: "Mittel",
    category: "Hauptgericht",
    rating: 4.8,
    isFavorite: false,
    nutritionalInfo: { calories: 520, protein: 22, carbs: 65, fat: 18 },
    ingredients: [
      "400g Spaghetti",
      "200g Pancetta oder Speck",
      "4 Eigelb",
      "100g Parmesan",
      "Schwarzer Pfeffer",
      "Salz",
    ],
    instructions: [
      "Spaghetti in Salzwasser kochen",
      "Pancetta in der Pfanne anbraten",
      "Eigelb mit Parmesan vermengen",
      "Pasta mit Pancetta mischen",
      "Ei-Käse-Mischung unterrühren",
    ],
  },
  {
    id: 2,
    title: "Chicken Tikka Masala",
    description: "Würziges indisches Curry mit zartem Hähnchen",
    image: "/placeholder.svg?height=200&width=300",
    cookTime: 45,
    servings: 6,
    difficulty: "Mittel",
    category: "Hauptgericht",
    rating: 4.6,
    isFavorite: false,
    nutritionalInfo: { calories: 380, protein: 28, carbs: 12, fat: 24 },
    ingredients: [
      "800g Hähnchenbrust",
      "400ml Kokosmilch",
      "400g Tomaten",
      "2 Zwiebeln",
      "Ingwer, Knoblauch",
      "Garam Masala, Kurkuma",
    ],
    instructions: [
      "Hähnchen marinieren",
      "Zwiebeln anbraten",
      "Gewürze hinzufügen",
      "Tomaten und Kokosmilch zugeben",
      "Hähnchen garen",
    ],
  },
  {
    id: 3,
    title: "Schokoladen-Brownies",
    description: "Saftige Brownies mit intensivem Schokoladengeschmack",
    image: "/placeholder.svg?height=200&width=300",
    cookTime: 35,
    servings: 12,
    difficulty: "Einfach",
    category: "Dessert",
    rating: 4.9,
    isFavorite: false,
    nutritionalInfo: { calories: 285, protein: 4, carbs: 32, fat: 16 },
    ingredients: ["200g dunkle Schokolade", "150g Butter", "200g Zucker", "3 Eier", "100g Mehl", "Prise Salz"],
    instructions: [
      "Schokolade und Butter schmelzen",
      "Zucker und Eier vermengen",
      "Schokoladenmischung unterrühren",
      "Mehl einarbeiten",
      "30 Min bei 180°C backen",
    ],
  },
  {
    id: 4,
    title: "Caesar Salad",
    description: "Knackiger Römersalat mit cremigem Caesar-Dressing",
    image: "/placeholder.svg?height=200&width=300",
    cookTime: 15,
    servings: 4,
    difficulty: "Einfach",
    category: "Vorspeise",
    rating: 4.3,
    isFavorite: false,
    nutritionalInfo: { calories: 180, protein: 8, carbs: 12, fat: 12 },
    ingredients: ["2 Römersalat-Köpfe", "100g Parmesan", "Croutons", "Mayonnaise", "Sardellen", "Zitronensaft"],
    instructions: [
      "Salat waschen und zerteilen",
      "Dressing aus Mayo, Sardellen und Zitrone",
      "Salat mit Dressing mischen",
      "Parmesan und Croutons darüber",
      "Sofort servieren",
    ],
  },
  {
    id: 5,
    title: "Beef Tacos",
    description: "Mexikanische Tacos mit gewürztem Rindfleisch",
    image: "/placeholder.svg?height=200&width=300",
    cookTime: 25,
    servings: 4,
    difficulty: "Einfach",
    category: "Hauptgericht",
    rating: 4.5,
    isFavorite: false,
    nutritionalInfo: { calories: 320, protein: 24, carbs: 28, fat: 14 },
    ingredients: ["500g Rinderhack", "8 Taco-Schalen", "Tomaten", "Zwiebeln", "Käse", "Taco-Gewürz"],
    instructions: [
      "Hackfleisch anbraten",
      "Taco-Gewürz hinzufügen",
      "Gemüse vorbereiten",
      "Taco-Schalen erwärmen",
      "Tacos befüllen und servieren",
    ],
  },
  {
    id: 6,
    title: "Apfelstrudel",
    description: "Traditioneller österreichischer Apfelstrudel",
    image: "/placeholder.svg?height=200&width=300",
    cookTime: 60,
    servings: 8,
    difficulty: "Schwer",
    category: "Dessert",
    rating: 4.7,
    isFavorite: false,
    nutritionalInfo: { calories: 245, protein: 3, carbs: 42, fat: 8 },
    ingredients: ["6 Äpfel", "Strudelteig", "Butter", "Semmelbrösel", "Zucker", "Zimt"],
    instructions: [
      "Äpfel schälen und schneiden",
      "Teig ausrollen",
      "Füllung vorbereiten",
      "Strudel rollen",
      "45 Min bei 180°C backen",
    ],
  },
]; 